const router = require('express').Router();

// require in our datetime shared function
const datetime = require('../util/datetime');

// require in our mock data to support our API responses
const questions = require('../../../mock_data/questions.json');

// GET /questions
router.get('/', (req, res) => {
    res.json(questions);
});

// POST /questions
router.post('/', (req, res) => {
    const { body } = req;

    // when we have a data store our id will be generated by Mongo DB
    // for now mock id generation
    const id = questions.length + 1;

    // TODO - a question is added to a quiz upon creation

    res.json({ ...body, id });
});
