const router = require('express').Router();

const Quiz = require('../controllers/quiz');
// require in our mock data to support our API responses
const quizzes = [{}];

// GET /quizzes
router.get('/', Quiz.getQuiz);

// POST /quizzes
router.post('/', (req, res) => {
    const { body } = req;

    // when we have a data store our id will be generated by Mongo DB
    // for now mock id generation
    const id = quizzes.length + 1;

    res.json({ ...body, id });
});

// GET /quizzes/:id
router.get('/:id', Quiz.getQuizById);

// PUT /quizzes/:id
router.put('/:id', (req, res) => {
    const { params, body } = req;
    const id = params.id;

    // find a quiz by its id
    // when we have a database we will query this from Mongo
    const quiz = quizzes.find((quiz) => {
        return quiz.id === parseInt(id);
    });

    // call helper function to get current year-month-day
    const today = datetime.getYearMonthDay();

    if (quiz) {
        if (today > quiz.start) {
            res.status(403).json({
                error: `Cannot edit quiz with start time of ${quiz.start}`,
            });
        } else {
            res.json({ ...quiz, ...body });
        }
    } else {
        res.status(404).json({ error: `Quiz by id ${id} not found.` });
    }
});

// DELETE /quizzes/:id
router.delete('/:id', (req, res) => {
    const { params } = req;
    const id = params.id;

    // find a quiz by its id
    // when we have a database we will query this from Mongo
    const quiz = quizzes.find((quiz) => {
        return quiz.id === parseInt(id);
    });

    // call helper function to get current year-month-day
    const today = datetime.getYearMonthDay();

    if (quiz) {
        if (today > quiz.start) {
            res.status(403).json({
                error: `Cannot delete quiz with start time of ${quiz.start}`,
            });
        } else {
            res.json({ deleted: { name: quiz.name, id: quiz.id } });
        }
    } else {
        res.status(404).json({ error: `Quiz by id ${id} not found.` });
    }
});

module.exports = router;
